# site settings
title: "Project Documentation"
description: "A short catchphrase or description of your project."
baseurl: "/remal-services"

# theme settings
# theme: jekyll-theme-minimal
remote_theme: jekyll-theme-cayman

# required plugins
#plugins:
#  - jekyll-remote-theme

nav_order:
  - index.md
  - api.md
  - setup.md
