# site settings
title: "Project Documentation"
description: "A short catchphrase or description of your project."
baseurl: "/remal-services"

# theme settings
# remote_theme: just-the-docs/just-the-docs@v0.9.0
remote_theme: mmistakes/minimal-mistakes@4.28.1
nav_sort: page_order

# required plugins
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
