# site settings
url: "https://zappee.github.io"
baseurl: "remal-services"
repository: "zappee/remal-services"
name: "Arnold Somogyi"

title: "Project Documentation"
subtitle: "Version 2.0"
description: "A short catchphrase or description of your project."
title_separator: "|"

# theme settings
# remote_theme: just-the-docs/just-the-docs@v0.9.0
remote_theme: mmistakes/minimal-mistakes@4.28.1
nav_sort: page_order


site_navigation: main

include:
  - _pages
  - assets

logo: "assets/images/remal-logo.jpg"


# required plugins
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
